feat: migrate to v4
nextauthjs/next-auth-typescript-example pull request #8
Opened 2021-08-11 20:24 UTC by ndom91

Migrated everything that needs changed so far. 

I did, however, run into one console error regarding `jwt` that I wasn't sure about. Maybe I forgot to migrate something? 

For example, on the "API" page of the example app, which is supposed to print the current session and jwt info, I get the following in my node console:

```bash
event - build page: /api/examples/jwt
TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of SecretKeyObject, ArrayBuffer, TypedArray, DataView, or Buffer. Received undefined
    at Object.hkdfSync (node:internal/crypto/hkdf:134:7)
    at hkdf (/opt/ndomino/next-auth-typescript-example/node_modules/next-auth/dist/lib/jwt.js:127:40)
    at getDerivedSigningKey (/opt/ndomino/next-auth-typescript-example/node_modules/next-auth/dist/lib/jwt.js:143:18)
    at decode (/opt/ndomino/next-auth-typescript-example/node_modules/next-auth/dist/lib/jwt.js:81:96)
    at getToken (/opt/ndomino/next-auth-typescript-example/node_modules/next-auth/dist/lib/jwt.js:109:12)
    at jwt (webpack-internal:///./pages/api/examples/jwt.ts:11:78)
    at Object.apiResolver (/opt/ndomino/next-auth-typescript-example/node_modules/next/dist/server/api-utils.js:101:15)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async DevServer.handleApiRequest (/opt/ndomino/next-auth-typescript-example/node_modules/next/dist/server/next-server.js:760:9)
    at async Object.fn (/opt/ndomino/next-auth-typescript-example/node_modules/next/dist/server/next-server.js:651:37) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

On both the normal and typescript example apps btw.

Any idea whats going on there? Did I miss something in terms of the migration?

Obviously there will probably be a few more small things to change before this is really up to snuff for `v4.0.0` (final), but hopefully this takes care of most of the work and then we can merge this PR whenever the day comes :tada:

2021-08-31 14:26 UTC, Frikki approved these changes

2021-09-17 11:40 UTC, lluia approved these changes
Apologies for the delay reviewing this 🙏🏽 , great work 💯 ⭐

2021-11-23 00:31 UTC, balazsorban44 requested changes
Could you update this to use `beta.7` To be ready for merge?

2021-11-23 22:52 UTC, ndom91 commented
@balazsorban44 also updated this PR to `beta.7` :+1:

2021-12-01 15:58 UTC, merged

2022-01-17 04:12 UTC, nyedidikeke commented
@ndom91 @lluia  How to use `options` without build error? https://github.com/nextauthjs/next-auth-typescript-example/commit/6752a9195e41deddde11c0776c5cf9b2a6b9d233

```sh
> tsc
pages/_app.tsx:26:9 - error TS2322: Type '{ children: Element[]; options: { staleTime: number; refetchInterval: number; }; session: any; }' is not assignable to type 'IntrinsicAttributes & SessionProviderProps'.
  Property 'options' does not exist on type 'IntrinsicAttributes & SessionProviderProps'.

26         options={{
           ~~~~~~~
```

2022-01-17 13:04 UTC, balazsorban44 commented
@there is no `options` in v4

2022-01-17 17:19 UTC, ndom91 commented
See migration docs: https://next-auth.js.org/getting-started/upgrade-v4#sessionprovider